# Generated by Django 5.0.6 on 2024-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
    ]
